version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'

      MYSQL_USER: 'user'

      MYSQL_PASSWORD: 'password'

      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    links:
      - db
    expose:
      - '5065'
    networks:
      - my_net

volumes:
  db_data:

networks:
  my_net:
    internal: true
